# Generated by Django 5.2.6 on 2026-02-26 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='产品名称')),
                ('product_type', models.CharField(choices=[('PLATFORM_SOFTWARE', '平台软件'), ('PC_TERMINAL_SOFTWARE', 'PC终端软件'), ('HARDWARE', '硬件'), ('STANDALONE_SOFTWARE', '单机板软件'), ('MOBILE_APP', '移动APP')], max_length=30, verbose_name='产品类型')),
                ('product_description', models.TextField(blank=True, null=True, verbose_name='产品说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=100, verbose_name='组件名称')),
                ('component_type', models.CharField(choices=[('SOFTWARE_MODULE', '软件模块'), ('HARDWARE', '硬件')], max_length=20, verbose_name='组件类型')),
                ('component_description', models.TextField(blank=True, null=True, verbose_name='组件说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='Products.product', verbose_name='所属产品')),
            ],
            options={
                'verbose_name': '产品组件',
                'verbose_name_plural': '产品组件',
                'ordering': ['-created_at'],
            },
        ),
    ]
