# Generated by Django 5.2.6 on 2026-02-27 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_vendor_product_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
    ]
