# Generated by Django 5.2.6 on 2026-02-26 14:54

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admindiv',
            options={'verbose_name': '行政区划', 'verbose_name_plural': '行政区划'},
        ),
        migrations.AddField(
            model_name='admindiv',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admindiv',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admindiv',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admindiv',
            name='level',
            field=models.IntegerField(default=0, editable=False, verbose_name='层级'),
        ),
        migrations.AlterField(
            model_name='admindiv',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='行政区划名称'),
        ),
        migrations.AlterField(
            model_name='admindiv',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Customers.admindiv', verbose_name='父级行政区划'),
        ),
    ]
