# Generated by Django 5.2.6 on 2026-02-27 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0002_alter_admindiv_options_admindiv_lft_admindiv_rght_and_more'),
        ('Products', '0002_vendor_product_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='产品名称')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='采购时间')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Customers.customer', verbose_name='客户')),
                ('integrator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrated_products', to='Products.vendor', verbose_name='集成商')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.vendor', verbose_name='厂商')),
            ],
            options={
                'verbose_name': '客户产品采购信息',
                'verbose_name_plural': '客户产品采购信息',
                'ordering': ['-created_at'],
            },
        ),
    ]
