# Generated by Django 5.2.6 on 2026-02-27 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0003_customerproduct'),
        ('Products', '0002_vendor_product_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerproduct',
            name='product_name',
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.product', verbose_name='产品'),
        ),
    ]
