# Generated by Django 5.2.6 on 2026-02-27 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0004_remove_customerproduct_product_name_and_more'),
        ('Products', '0004_productmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='product_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.productmodel', verbose_name='产品型号'),
        ),
    ]
