# Generated by Django 5.2.6 on 2026-02-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0005_remove_customerproduct_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='intro',
            field=models.TextField(blank=True, null=True, verbose_name='客户简介'),
        ),
    ]
