# Generated by Django 5.2.6 on 2026-02-28 07:08

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0006_customer_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='intro',
            field=markdownx.models.MarkdownxField(blank=True, null=True, verbose_name='客户简介'),
        ),
    ]
